import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {useTheme as useNextTheme} from 'next-themes';
import {Switch, useTheme} from '@nextui-org/react';

const Home: NextPage = () => {
   const {setTheme} = useNextTheme();
   const {isDark, type} = useTheme();

   return (
      <div>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Switch
            checked={isDark}
            onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
         />
      </div>
   );
};

export default Home;
